services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus-local.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/rules.yml:/etc/prometheus/rules.yml
    networks:
      - monitoring
  exporter:
    container_name: exporter
    build:
      context: .
      dockerfile: ./exporter/Dockerfile
    ports:
      - 9080:9080
    depends_on:
      - prometheus
    networks:
      - monitoring
networks:
  monitoring:
    driver: bridge