name: Deploy Infrastructure

on:
    workflow_dispatch: 

permissions: 
    id-token: write
    contents: read

jobs:
    deploy-infra:
        runs-on: ubuntu-latest
        environment: dev
        steps:
            - name: Login to Azure
              uses: azure/login@v2
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRITION_ID }}
                enable-AzPSSession: true
            
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Deploy Infrastructure
              uses: azure/powershell@v2
              with:
                azPSVersion: "latest"
                inlineScript: |
                    chmod +x ${{ github.workspace }}/scripts/deployInfra.ps1
                    ${{ github.workspace }}/scripts/deployInfra.ps1
