name: Deploy Infrastructure

on:
    workflow_dispatch: 

permissions: 
    id-token: write
    contents: read

jobs:
    deploy-infra:
        runs-on: 'ubunut-latest'
        environment: 'dev'
        steps:
            - name: Login to Azure
              uses: azure/login@v1
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRITION_ID }}
                enable-AzPSSession: true
            
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Deploy Config
              uses: azure/CLI@v1
              with:
                azcliversion: 2.53.0
                inlineScript: |
                    ${{ github.workspace }}/scripts/deployInfra.ps1
