name: Deploy Platform Monitor

on:
    workflow_dispatch: 

permissions: 
    id-token: write
    contents: read

jobs:
    deploy-platform-monitor:
        runs-on: ubuntu-latest
        environment: dev
        steps:
            - name: Login to Azure
              uses: azure/login@v2
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRITION_ID }}

            - name: Checkout Repo
              uses: actions/checkout@v4
        
            - name: Login to ACR
              uses: docker/login-action@v3
              with:
                registry: pmacrwesteu.azurecr.io
                username: ${{ secrets.ACR_USER }}
                password: ${{ secrets.ACR_PASSWORD }}

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                context: .
                file: ${{ github.workspace }}/platformmonitor/exporter/Dockerfile
                push: true
                tags: pmacrwesteu.azurecr.io/exporter:latest