name: Deploy Platform Monitor

on:
    workflow_dispatch: 

permissions: 
    id-token: write
    contents: read

jobs:
    deploy-infra:
        runs-on: ubuntu-latest
        environment: dev
        steps:
            - name: Login to Azure
              uses: azure/login@v2
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRITION_ID }}
                enable-AzPSSession: true
