name: Deploy Platform Monitor

on:
    workflow_dispatch: 

permissions: 
    id-token: write
    contents: read

jobs:
    deploy-platform-monitor:
        runs-on: ubuntu-latest
        environment: dev
        steps:
            - name: Login to Azure
              uses: azure/login@v2
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRITION_ID }}

            - name: Checkout Repo
              uses: actions/checkout@v4
        
            - name: Login to ACR
              uses: docker/login-action@v3
              with:
                registry: pmacrwesteu.azurecr.io
                username: ${{ secrets.ACR_USER }}
                password: ${{ secrets.ACR_PASSWORD }}

            # - name: Build and push
            #   uses: docker/build-push-action@v6
            #   with:
            #     context: ${{ github.workspace }}/Platformmonitor/exporter
            #     file: ${{ github.workspace }}/Platformmonitor/exporter/Dockerfile
            #     push: true
            #     tags: pmacrwesteu.azurecr.io/exporter:latest

            - name: Upload Prometheus config file
              uses: azure/cli@v2
              with:
                azcliversion: latest
                inlineScript: |
                    az storage file upload --account-key ${{ secrets.ACCOUNT_KEY }} --account-name pmsawesteu --share-name config --source ${{ github.workspace }}/Platformmonitor/prometheus/prometheus.yml --path prometheus/prometheus.yml